### ISSUE TITLE
Confused with suitescript/no-log-module

### ISSUE THREAD

**Issue by dels07** [adamdavies001/eslint-plugin-suitescript#1]
Hi,

I confused with `suitescript/no-log-module` rule, on why we prefer to use global log object instead of netsuite `N/log` module, since I didn't found any mention regarding this in suitescript documentation.

Thanks,
Dels

**Comment by adamdavies001** [comment]
The Log object is globally available in all scripts automatically without the use of the N/log module.

The only times it's necessary are either to create logs on a script from an attached client script or for testing purposes. I'm planning on adding a configuration to account for the former option, and I'd recommend overriding this rule (turning it off) altogether for testing purposes.
